### ISSUE TITLE
Error this might be becouse my host updated to java 9.

### ISSUE THREAD

**Issue by arturek1666** [Lubenica98/FairPlayMinecraft#124]
using: 5.9.2
Paperspigot 1.12.2

[K[31;1m[18:39:55 ERROR]: Could not pass event LoginEvent to FairPlayMinecraft v5.9.2
java.lang.NoClassDefFoundError: fr/xephi/authme/api/API
        at ovh.minex.hooks.AuthMe.onPlayerJoin(AuthMe.java) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor299.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1232]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1232]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1232]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) ~[patched_1.12.2.jar:git-Paper-1232]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) ~[patched_1.12.2.jar:git-Paper-1232]
        at fr.xephi.authme.service.BukkitService.callEvent(BukkitService.java:281) ~[?:?]
        at fr.xephi.authme.process.login.ProcessSyncPlayerLogin.processPlayerLogin(ProcessSyncPlayerLogin.java:89) ~[?:?]
        at fr.xephi.authme.process.SyncProcessManager.lambda$processSyncPlayerLogin$3(SyncProcessManager.java:51) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) [patched_1.12.2.jar:git-Paper-1232]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [patched_1.12.2.jar:git-Paper-1232]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [patched_1.12.2.jar:git-Paper-1232]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1232]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1232]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1232]
        at java.lang.Thread.run(Thread.java:844) [?:?]
Caused by: java.lang.ClassNotFoundException: fr.xephi.authme.api.API
        at java.net.URLClassLoader.findClass(URLClassLoader.java:466) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:105) ~[patched_1.12.2.jar:git-Paper-1232]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:90) ~[patched_1.12.2.jar:git-Paper-1232]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:563) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:496) ~[?:?]
        ... 17 more
[39;0m

**Comment by arturek1666** [comment]
By the way the bata work's. But I don't want to use beta yet?

**Comment by arturek1666** [comment]
By the way when try the beta the FPMC_win_BETA.exe don't detects that i have minecraft running and that i am already on server just so you know xD

**Comment by Lubenica98** [comment]
Fixed in the stable 6.0.0 version.
