### ISSUE TITLE
Error ondisable?

### ISSUE THREAD

**Issue by Lubenica98** [Lubenica98/FairPlayMinecraft#134]
```
[18:18:07] [Server thread/INFO]: Saving...
[18:18:07] [Server thread/INFO]: Saved the world
[18:18:07] [Server thread/INFO]: Stopping the server
[18:18:07] [Server thread/INFO]: Stopping server
[18:18:07] [Server thread/INFO]: [FairPlayMinecraft] Disabling FairPlayMinecraft v6.0.1
[18:18:08] [FairPlayMinecraft] Plugin FairPlayMinecraft v6.0.1 generated an exception while executing task 407488
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:403) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:126) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.scheduleSyncRepeatingTask(CraftScheduler.java:122) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.scheduleSyncDelayedTask(CraftScheduler.java:105) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.scheduleSyncDelayedTask(CraftScheduler.java:88) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
    at ovh.minex.connection.Communication$a.run(Communication$a.java) ~[?:?]
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

**Comment by Lubenica98** [comment]
config.yml:
```
##################################################################################################################################
# FairPlayMinecraft configuration file #
# #
# If you need any help regarding the plugin feel free to contact me here: https://www.spigotmc.org/conversations/add?to=Lubenica #
##################################################################################################################################

# Do you want your players to be asked for the check on join?
check_on_join: true
# Do you want to be able to use /fpmc check <nick> command instead of forcing players to go through the check on join?
# This could be a better and simplier alternative to screensharing many servers are nowadays using to check their players for cheats
check_command_enabled: false
# Remove player from checking queue (if he was added to it using /fpmc check <nick> command) when he leaves the server
remove_from_queue_on_leave: false
# Set to true if you want the checking process to be optional.
checking_optional: false
# Set to true for things that you would like to be forbidden while waiting for player to run the application
restrictions:
# Players won't be able to move when set to true
movement: true
# Players won't be able to send messages when set to true
chat: false
# Players won't be able to execute commands when set to true
commands: true
# Players won't be able to throw items from inventory when set to true
protect_inventory: true
# Players won't be able to interact with signs, buttons etc. when set to true
interactions: true
# Players won't be attacked by monsters when set to true
protect_from_monsters: true
# Players won't be able to open the inventory when set to true
inventory_open: true
# Message that will be sent to the player after he goes through the check and doesn't have a cheat 
messages:
success: '&aPotvrdio si da si posten, mozes nastaviti sa igrom. Hvala &c<3'
# Command(s) that will be executed if player tries to join the server using cheats
punishment:
command:
- kick %player% nije dozvoljeno koristiti cit!
- ''
- ''
# Command(s) that will be executed if player does not have a cheat 
no_cheat_command:
- ''
- '' 
# Set to true if you want your admins who have fpmc.notify permission to be notified if someone tries to join using a cheat
notify_admins:
enabled: true
# Message which will be sent to the admins (%player% will be replaced with player's name, %clientname% will be replaced with the client name)
message: '&c%player% &7je pokusao uci sa citom &3&l(&c%clientname%&3&l)'
# Set true if you want all attempts of joining using a cheat to be logged to log.txt file
logging_enabled: true
# Should instructions for running the application be autobroadcasted to player every x ticks? (20 ticks = 1 second)
autobroadcast:
enabled: true
interval: '600'
# If you are running this server under BungeeCord, you HAVE TO enable BungeeCord support!
# First put this plugin (FPMC_plugin.jar) in "plugins" folder in your BungeeCord. Then start BungeeCord and stop it.
# A config file will be generated located in /plugins/FairPlayMinecraft/config.yml.
# Open the config.yml file and set "port" to some unused port or just leave it like it is
bungeecord_support:
# Set to true to enable
enabled: false
# Put in the IP address and port of your BungeeCord instance which you are using to connect to in game in format IP:pORT.
# For example if you are connecting in the game to 172.16.254.1:25565, put this in
address: ''
# Set this to the IP address of your BungeeCord instance. For example if you are hosting both the server and BungeeCord
# on the same machine, put in "localhost"
ip: 'localhost'
# Set to port you defined in config.yml in your BungeeCord
port: 11414
# If you have the plugin on more than one server and want players to have to go through check only once per session, set this to true
one_check_per_session: true
# If you have multiple IP addresses using which you can join your server, list them here in format IP:pORT
multiple_ips:
- ''
- ''
# Enable if you made your custom versions filter (http://fairplayminecraft.com/filter/versions.php)
use_custom_versions_filter: false
# Enable if you want Forge to be enabled on your server (you have to create a mods filter first - http://fairplayminecraft.com/filter/forge.php)
use_filter_for_forge: false
# Enable if you want LiteLoader to be allowed on your server (you have to create a mods filter first - http://fairplayminecraft.com/filter/liteloader.php)
use_filter_for_liteloader: false
# List commands which will be executed on the Spigot server when player who is in a queue for the check (when using /fpmc check command)
# leaves the server during the check
left_during_check_punishment_command_spigot:
- ''
- ''
# List commands which will be executed on the BungeeCord instance when player who is in a queue for the check (when using /fpmc check command)
# leaves the server during the check
left_during_check_punishment_command_bungeecord:
- ''
- ''
# List commands which will be executed right when player is asked to go through the check
command_before_check:
- ''
- '' 
# If you want your players not to be checked on every join, but every x join, set a number here
check_every_x_join: 0
# If you want your players not to be checked on every join, but be checked in case of x%, set a number here (1-100)
x_chance_to_be_checked: 0
# If you want titles to be showed when a player is asked to go through the check, set "enabled" to true
titles:
enabled: true
title: '&4&l[&aAnti-Cheat&4&l]'
subtitle: '&3&lProcitaj chat &4&l<3'
# Duration how long the title will be visible (in seconds)
duration: 15 
# If you want to limit number of times a player can be checked in one session using /fpmc check command, set a number here
max_checks_per_session: 0
# Set 'enabled' to true if you want a sound to be played to a player who goes through the check without using a cheat
sound_nocheat:
enabled: true
# Put in value of a sound which you can find here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
sound: 'ENTITY_PLAYER_LEVELUP'
# Do you want a command to be executed if player doesn't finish the checking within a specified time
command_if_not_done:
# Set to true to enable
enabled: false
# Which commands will be executed (%player% replaces player's name)
commands:
- ''
# If the player doesn't finish the check within a time, the specified command will be executed (in seconds!)
time: 60
# Commands which will be executed when player joins the server no matter if he is asked to go through the check or not
on_join_commands:
- ''
- ''
# Set to true if you want to be able to remove a player from queue by typing /fpmc check <nick> command (again)
queue_command_remove: true
# Commands which will be executed when player leaves the server no matter if he was asked to go through the check or not
on_leave_commands:
- ''
- ''
```
