### ISSUE TITLE
serious problem

### ISSUE THREAD

**Issue by MineFriend** [Lubenica98/FairPlayMinecraft#140]
your plugin does not work anymore ... precisely it does not work anymore with bungeecord

**Comment by MineFriend** [comment]
gives me this error every time I close bungeecord "[FairPlayMinecraft] [FairPlayMinecraft] Can not connect to the main server!"

**Comment by MineFriend** [comment]
console bungeecord : Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@62ef069e, id=31, owner=ovh.minex.bungee.Bungee@68844523, task=ovh.minex.bungee.Bungee$c@61548314, delay=0, period=0, running=true) encountered an exception
java.lang.NullPointerException
    at ovh.minex.bungee.Bungee$c.run(Bungee$c.java)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)

**Comment by MineFriend** [comment]
https://hastebin.com/owixuceraj.rb

**Comment by Lubenica98** [comment]
Sorry for the late response, seems like you have set a firewall on your Bungee node?
