### ISSUE TITLE
Autobroadcast trowing some errors?

### ISSUE THREAD

**Issue by Lubenica98** [Lubenica98/FairPlayMinecraft#38]
```
[00:57:01 WARN]: Exception in thread "Craft Scheduler Thread - 208"
[00:57:01 WARN]: org.apache.commons.lang.UnhandledException: Plugin FairPlayMinecraft v5.3.5 generated an exception while executing task 98
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at ovh.minex.FPMC$0.run(FPMC$0.java)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
```

**Comment by Lubenica98** [comment]
Should be fixed in 5.4.1, waiting for confirmation from users who were having this issue
