### ISSUE TITLE
Errors when running with BungeeCord

### ISSUE THREAD

**Issue by Lubenica98** [Lubenica98/FairPlayMinecraft#39]
BungeeCord side:
```
20:29:43 [SEVERE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@7530ad9c, id=0, owner=ovh.minex.hooks.Bungee@544fa968, task=ovh.minex.hooks.Bungee$1@58a9760d, delay=0, period=0, running=true) encountered an exception
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
at java.lang.String.substring(Unknown Source)
at ovh.minex.hooks.Bungee$1.run(Bungee.java:75)
at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
```
Spigot side:
```
[20:35:27 WARN]: [FairPlayMinecraft] Plugin FairPlayMinecraft v5.3.6 generated an exception while executing task 2
java.lang.NullPointerException
at ovh.minex.FPMC$0.run(FPMC$0.java) ~[?:?]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-7d78b81-e2a288c]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-7d78b81-e2a288c]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_111]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_111]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
```
```
4:35:37 WARN]: java.net.ConnectException: Connection refused (Connection refused)
[14:35:37 WARN]:        at java.net.PlainSocketImpl.socketConnect(Native Method)
[14:35:37 WARN]:        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[14:35:37 WARN]:        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[14:35:37 WARN]:        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[14:35:37 WARN]:        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[14:35:37 WARN]:        at java.net.Socket.connect(Socket.java:589)
[14:35:37 WARN]:        at java.net.Socket.connect(Socket.java:538)
[14:35:37 WARN]:        at java.net.Socket.<init>(Socket.java:434)
[14:35:37 WARN]:        at java.net.Socket.<init>(Socket.java:211)
[14:35:37 WARN]:        at ovh.minex.BungeeConnection.sendreceive(BungeeConnection.java)
[14:35:37 WARN]:        at ovh.minex.events.QuitEvent.onPlayerQuit(QuitEvent.java)
[14:35:37 WARN]:        at sun.reflect.GeneratedMethodAccessor149.invoke(Unknown Source)
[14:35:37 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:35:37 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[14:35:37 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300)
[14:35:37 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[14:35:37 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[14:35:37 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501)
[14:35:37 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486)
[14:35:37 WARN]:        at net.minecraft.server.v1_8_R3.PlayerList.disconnect(PlayerList.java:364)
[14:35:37 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:875)
[14:35:37 WARN]:        at net.minecraft.server.v1_8_R3.NetworkManager.l(NetworkManager.java:314)
[14:35:37 WARN]:        at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:145)
[14:35:37 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:875)
[14:35:37 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[14:35:37 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[14:35:37 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[14:35:37 WARN]:        at java.lang.Thread.run(Thread.java:745)
```

**Comment by Lubenica98** [comment]
Will be fixed in 3.4.0
