### ISSUE TITLE
Notify when BungeeCord support wasn't configured correctly

### ISSUE THREAD

**Issue by Lubenica98** [Lubenica98/FairPlayMinecraft#49]
Instead of throwing an error:

```
[16:09:53] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to FairPlayMinecraft v5.4.0
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
    at net.minecraft.server.v1_11_R1.PlayerList.onPlayerJoin(PlayerList.java:327) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
    at net.minecraft.server.v1_11_R1.PlayerList.a(PlayerList.java:160) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
    at net.minecraft.server.v1_11_R1.LoginListener.b(LoginListener.java:147) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
    at net.minecraft.server.v1_11_R1.LoginListener.F_(LoginListener.java:57) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
    at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:233) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
    at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:140) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
    at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:834) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
    at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
    at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
    at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_112]
Caused by: java.lang.NullPointerException
    at ovh.minex.events.JoinEvent.onPlayerJoin(JoinEvent.java) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_112]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_112]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_112]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
    ... 14 more
```

**Comment by Lubenica98** [comment]
Added/fixed in 5.4.1
