### ISSUE TITLE
Error when using BungeeCord mode on multiple servers

### ISSUE THREAD

**Issue by Lubenica98** [Lubenica98/FairPlayMinecraft#93]
```
FairPlayMinecraft] Task #1197 for FairPlayMinecraft v5.8.3 generated an exception
java.lang.NullPointerException
        at ovh.minex.FPMC.doPlayer(FPMC.java) ~[?:?]
        at ovh.minex.connection.MessageProcess$0$1.run(MessageProcess$0$1.java) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [Spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Spigot.jar:git-Spigot-21fe707-e1ebe52]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

**Comment by Lubenica98** [comment]
Fixed in the upcoming version.
